name: TorosamyReward
version: '1.0-SNAPSHOT'
main: net.torosamy.torosamyReward.TorosamyReward
api-version: '1.13'
authors: [ Torosamy,yweiyang ]
website: https://www.torosamy.net
depend:
  - TorosamyCore
  - PlaceholderAPI
